export const APPOINT_CREATE_REQUEST = 'APPOINT_CREATE_REQUEST';
export const APPOINT_CREATE_SUCCESS = 'APPOINT_CREATE_SUCCESS';
export const APPOINT_CREATE_FAIL = 'APPOINT_CREATE_FAIL';
export const APPOINT_CREATE_RESET = 'APPOINT_CREATE_RESET';
export const APPOINT_PAY_REQUEST = 'APPOINT_PAY_REQUEST';
export const APPOINT_PAY_SUCCESS = 'APPOINT_PAY_SUCCESS';
export const APPOINT_PAY_FAIL = 'APPOINT_PAY_FAIL';
export const APPOINT_PAY_RESET = 'APPOINT_PAY_RESET';

export const APPOINT_DELIVER_REQUEST = 'APPOINT_DELIVER_REQUEST';
export const APPOINT_DELIVER_SUCCESS = 'APPOINT_DELIVER_SUCCESS';
export const APPOINT_DELIVER_FAIL = 'APPOINT_DELIVER_FAIL';
export const APPOINT_DELIVER_RESET = 'APPOINT_DELIVER_RESET';

export const APPOINT_DETAILS_REQUEST = 'APPOINT_DETAILS_REQUEST';
export const APPOINT_DETAILS_SUCCESS = 'APPOINT_DETAILS_SUCCESS';
export const APPOINT_DETAILS_FAIL = 'APPOINT_DETAILS_FAIL';

export const APPOINT_MINE_LIST_REQUEST = 'APPOINT_MINE_LIST_REQUEST';
export const APPOINT_MINE_LIST_SUCCESS = 'APPOINT_MINE_LIST_SUCCESS';
export const APPOINT_MINE_LIST_FAIL = 'APPOINT_MINE_LIST_FAIL';

export const APPOINT_LIST_REQUEST = 'APPOINT_LIST_REQUEST';
export const APPOINT_LIST_SUCCESS = 'APPOINT_LIST_SUCCESS';
export const APPOINT_LIST_FAIL = 'APPOINT_LIST_FAIL';

export const APPOINT_SUMMARY_REQUEST = 'APPOINT_SUMMARY_REQUEST';
export const APPOINT_SUMMARY_SUCCESS = 'APPOINT_SUMMARY_SUCCESS';
export const APPOINT_SUMMARY_FAIL = 'APPOINT_SUMMARY_FAIL';

export const APPOINT_DELETE_REQUEST = 'APPOINT_DELETE_REQUEST';
export const APPOINT_DELETE_SUCCESS = 'APPOINT_DELETE_SUCCESS';
export const APPOINT_DELETE_FAIL = 'APPOINT_DELETE_FAIL';
export const APPOINT_DELETE_RESET = 'APPOINT_DELETE_RESET';