export const PENDING_ADD_ITEM = 'PENDING_ADD_ITEM';
export const PENDING_REMOVE_ITEM = 'PENDING_REMOVE_ITEM';
export const PENDING_SAVE_SHIPPING_ADDRESS = 'PENDING_SAVE_SHIPPING_ADDRESS';
export const PENDING_SAVE_PAYMENT_METHOD = 'PENDING_SAVE_PAYMENT_METHOD';
export const PENDING_EMPTY = 'PENDING_EMPTY';